apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: grav-nav-multiplayer
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: grav-nav-cloud-run-sa@PROJECT_ID.iam.gserviceaccount.com
      containers:
      - image: us-east1-docker.pkg.dev/PROJECT_ID/grav-nav-repo/grav-nav-multiplayer:latest
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: '2'
            memory: 2Gi
        env:
        - name: PYTHON_ENV
          value: production
